### ISSUE TITLE
Базовые стили для тегов

### ISSUE THREAD

**Issue by bvlad05** [eugenegl/VEDHEM#6]
@eugenegl 

К тегам можно писать только те стили, которые повторяются.
```css
h1 {
   color: #EFBE4F;
   font-size: 72px;
   margin-bottom: 20px;
}
```
т.е можно прописать размер, толщину

а такие вещи как цвет, отступ снизу нужно задачать через классы модификаторы, например:
```css
h1 {
   font-size: 50px;
   font-weight: 700;
}

.color-yellow {
   color: #EFBE4F;
}

.color-white {
   color: #fff;
}

.mb-2 {
   margin-bottom: 20px;
}

```

```html
<h1 class="color-yellow">Hello</h1>
<h2 class="color-white mb-2">Some text</h2>
```
